apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      broker-id: "1"
  template:
    metadata:
      labels:
        app: kafka
        broker-id: "1"
    spec:
      hostname: broker-1
      containers:
        - name: kafka
          image: apache/kafka-native:4.1.0
          ports:
            - containerPort: 9092
              name: kafka
            - containerPort: 9192
              name: controller
          env:
            - name: CLUSTER_ID
              value: "ZBePkeofSja3lHvCKBB63w"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9192"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@broker-1.kafka:9192,2@broker-2.kafka:9193,3@broker-3.kafka:9194"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-1
---
# Kafka Broker 2 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      broker-id: "2"
  template:
    metadata:
      labels:
        app: kafka
        broker-id: "2"
    spec:
      hostname: broker-2
      containers:
        - name: kafka
          image: apache/kafka-native:4.1.0
          ports:
            - containerPort: 9093
              name: kafka
            - containerPort: 9193
              name: controller
          env:
            - name: CLUSTER_ID
              value: "ZBePkeofSja3lHvCKBB63w"
            - name: KAFKA_NODE_ID
              value: "2"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9093,CONTROLLER://:9193"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://:9093"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@broker-1.kafka:9192,2@broker-2.kafka:9193,3@broker-3.kafka:9194"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-2
---
# Kafka Broker 3 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      broker-id: "3"
  template:
    metadata:
      labels:
        app: kafka
        broker-id: "3"
    spec:
      hostname: broker-3
      containers:
        - name: kafka
          image: apache/kafka-native:4.1.0
          ports:
            - containerPort: 9094
              name: kafka
            - containerPort: 9194
              name: controller
          env:
            - name: CLUSTER_ID
              value: "ZBePkeofSja3lHvCKBB63w"
            - name: KAFKA_NODE_ID
              value: "3"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9094,CONTROLLER://:9194"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://:9094"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@broker-1.kafka:9192,2@broker-2.kafka:9193,3@broker-3.kafka:9194"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "2"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "3"
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data-3
