apiVersion: v1
kind: Service
metadata:
  name: broker-1
spec:
  selector:
    app: kafka
    broker-id: "1"
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
      #nodePort: 30092
      protocol: TCP
    - name: controller
      port: 9192
      targetPort: 9192
      protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: broker-2
spec:
  selector:
    app: kafka
    broker-id: "2"
  ports:
    - name: kafka
      port: 9093
      targetPort: 9093
      # nodePort: 30093
      protocol: TCP
    - name: controller
      port: 9193
      targetPort: 9193
      protocol: TCP
  #type: NodePort
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: broker-3
spec:
  selector:
    app: kafka
    broker-id: "3"
  ports:
    - name: kafka
      port: 9094
      targetPort: 9094
      # nodePort: 30094
      protocol: TCP
    - name: controller
      port: 9194
      targetPort: 9194
      protocol: TCP
  type: LoadBalancer
---
# Headless service for cluster discovery
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
---
